<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Gibbed.DeusEx3.DRMUnpack</RootNamespace>
    <AssemblyName>Gibbed.DeusEx3.DRMUnpack</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>..\bin_dx3\$(PlatformOutputFolder)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\bin_dx3_release\$(PlatformOutputFolder)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibbed.DeusEx3.FileFormats\Gibbed.DeusEx3.FileFormats.csproj" />
    <ProjectReference Include="..\Gibbed.IO\Gibbed.IO.csproj" />
    <ProjectReference Include="..\Texture.BCnE.NET.Codec\Texture.BCnE.NET.Codec.csproj" />
    <ProjectReference Include="..\NDesk.Options\NDesk.Options.csproj" />
  </ItemGroup>

</Project>
