<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Gibbed.TombRaider.Unpack</RootNamespace>
    <AssemblyName>Gibbed.TombRaider.Unpack</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>..\bin_tr\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\bin_tr_release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibbed.CrystalDynamics.FileFormats\Gibbed.CrystalDynamics.FileFormats.csproj" />
    <ProjectReference Include="..\Gibbed.IO\Gibbed.IO.csproj" />
    <ProjectReference Include="..\Gibbed.ProjectData\Gibbed.ProjectData.csproj" />
    <ProjectReference Include="..\NDesk.Options\NDesk.Options.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

</Project>
