<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Gibbed.CrystalDynamics.FileFormats</RootNamespace>
    <AssemblyName>Gibbed.CrystalDynamics.FileFormats</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibbed.IO\Gibbed.IO.csproj" />
  </ItemGroup>

</Project>
