<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Gibbed.TombRaider.DRMEdit</RootNamespace>
    <AssemblyName>Gibbed.TombRaider.DRMEdit</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>..\bin_tr\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\bin_tr_release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Be.Windows.Forms.HexBox">
      <HintPath>..\other\Be.Windows.Forms.HexBox.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gibbed.IO\Gibbed.IO.csproj" />
    <ProjectReference Include="..\Gibbed.Squish\Gibbed.Squish.csproj" />
    <ProjectReference Include="..\Gibbed.TombRaider.FileFormats\Gibbed.TombRaider.FileFormats.csproj" />
    <ProjectReference Include="..\NDesk.Options\NDesk.Options.csproj" />
  </ItemGroup>

</Project>
